export const SHEET_SCHEMA_VERSION = "1";

export const SHEET_TABS = {
  schemaMeta: "schema_meta",
  users: "users",
  activities: "activities",
  gymSessions: "gym_sessions",
  gymExercises: "gym_exercises",
  gymSets: "gym_sets",
  runs: "runs",
  bodyMeasurements: "body_measurements",
  goals: "goals",
} as const;

export const SHEET_HEADERS: Record<string, readonly string[]> = {
  [SHEET_TABS.schemaMeta]: ["key", "value", "updated_at"],
  [SHEET_TABS.users]: [
    "id",
    "google_subject",
    "email",
    "name",
    "avatar_url",
    "timezone",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  [SHEET_TABS.activities]: [
    "id",
    "user_id",
    "activity_type",
    "activity_date",
    "duration_seconds",
    "notes",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  [SHEET_TABS.gymSessions]: ["activity_id", "title", "location"],
  [SHEET_TABS.gymExercises]: [
    "id",
    "activity_id",
    "exercise_name",
    "muscle_group",
    "sequence_number",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  [SHEET_TABS.gymSets]: [
    "id",
    "exercise_id",
    "set_number",
    "reps",
    "weight_kg",
    "rpe",
    "completed",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  [SHEET_TABS.runs]: [
    "activity_id",
    "distance_meters",
    "run_type",
    "location",
    "rpe",
    "elevation_gain_meters",
  ],
  [SHEET_TABS.bodyMeasurements]: [
    "id",
    "user_id",
    "measured_at",
    "weight_kg",
    "body_fat_percent",
    "waist_cm",
    "notes",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  [SHEET_TABS.goals]: [
    "id",
    "user_id",
    "goal_type",
    "target_value",
    "unit",
    "period_type",
    "start_date",
    "end_date",
    "is_active",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
};
